### ISSUE TITLE
Every time I see the name I think 'vaporware'

### ISSUE THREAD

**Issue by sam-silv** [Shrugs/V-A-P-O-R-W-A-V-E#2] opened 2015-12-13 20:59 UTC
Can you confirm this is not, in fact, vaporware?

Thanks!

**Comment by shrugs** [comment] 2015-12-14 04:20
Pretty much any feature I promise after `init commit` is vaporware.

And I only mis-typed the name 5 times during development, so I'm closing this as "feature, not a bug".

**Closed as completed by shrugs** 2015-12-14 04:20 UTC

**Comment by sam-silv** [comment] 2015-12-14 18:59
:+1:
